### ISSUE TITLE
Packagist & namespace

### ISSUE THREAD

**Issue by jaimeperez** [UNINETT/flarum-ext-auth-dataporten#1]
Hi Simon!

I see you _hijacked_ the `uninett` namespace in packagist, and now we can't add packages there under that namespace 😢 

Can you either move this to the UNINETT organization or move your package to a different namespace so that we can claim it in packagist and publish our packages there?

Tusen takk! 😉

**Comment by skrodal** [comment]
Ohoy Jaime, 

My apologies; it was not my intention to hijack anything. Will try to set ownership of this repo to UNINETT now. Let me know if that resolves your problem.

Værsågod! :)

**Comment by jaimeperez** [comment]
Hei hei!

I know it wasn't, I was just joking 😉 

Thanks a lot for looking into it! Let us know if we need to do something (I guess we have to).

**Comment by jaimeperez** [comment]
I see you have moved it to the UNINETT organization, thanks Simon!

However, packagist keeps complaining about the organization being tied to you 😞  Could you please try removing the package and see if then we can add it tied to UNINETT?

**Comment by skrodal** [comment]
I just deleted the package from Packagist; my guess is that the `uninett` namespace is now available.

**Comment by jaimeperez** [comment]
That worked like a charm! I've also added back _uninett/flarum-ext-auth-dataporten_ to packagist in the _uninett_ namespace. Tusen takk Simon! 😄
